
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"

[[headers]]
  for = "/workers/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
